### ISSUE TITLE
Error on High Sierra

### ISSUE THREAD

**Issue by elcomix97edu** [MatthewPierson/1033-OTA-Downgrader#10]
I'm trying to run the script in High Sierra and all work but restore.sh give me this error:Reason: Incompatible library version: futurerestore requires version 6.0.0 or later, but libusbmuxd.4.dylib provides version 5.0.0

I need update my mac to Mojave or there is a way to execute the script in High Sierra

**Comment by MatthewPierson** [comment]
There is no High Sierra support as I can't test it due to only having Mojave machines.

**Comment by nikosntoykas** [comment]
This is very very sad. Gοοdbye 5s...... if Sierra is not supported why I'm losing my day today? Please write it to the description. THERE IS NO SIERRA SUPPORT.

**Comment by Merculous** [comment]
I'm working on a fix. It will fix most of the issues, if not all.

**Comment by mittovipi** [comment]
High sierra works fine

**Comment by mittovipi** [comment]
it needs a little modification to work on High Sierra

**Comment by consolelogluke** [comment]
What's the modification?

**Comment by nikosntoykas** [comment]
> it needs a little modification to work on High Sierra

oh yes;!

**Comment by mittovipi** [comment]
Work on High Sierra
http://bit.ly/highsierradowngrade

**Comment by mittovipi** [comment]
I am just a user. I am not a dev

**Comment by elcomix97edu** [comment]
> Work on High Sierra
> http://bit.ly/highsierradowngrade

I try your version and futurerestore load and inject iBEC correctly but now i have this errors:
ERROR: Unable to find required ApNonce in parameters
ERROR: Unable to add img4 tags to TSS request
[Error] ERROR: Unable to get signing tickets for SEP

**Comment by consolelogluke** [comment]
I’m getting the same issue as @elcomix97edu

**Comment by mittovipi** [comment]
move the ota.json file to / tmp on macos

**Comment by mittovipi** [comment]
Please try again
http://bit.ly/highsierradowngrade5s

**Comment by MatthewPierson** [comment]
@mittovipi What have you actually changed besides the language of the logs and the names of the scripts? After looking through them I can't find any changes at all that would indicate a fix for High Sierra machines. I would appreciate you not distributing edited copies of my scripts that claim to have changes that allow for more OS support when in reality they don't.

**Comment by consolelogluke** [comment]
@MatthewPierson It actually fixes the issue with High Sierra though, I got way further than I could before. In a minute I’ll try to find the changes.

**Comment by consolelogluke** [comment]
@mittovipi The same error happens with the second version.

**Comment by MatthewPierson** [comment]
Any changes you had with his “edits” are pure placebo. Check the files, there is no functional change to enable High Sierra support.

**Comment by mittovipi** [comment]
sorry.  I will delete all of them

**Comment by consolelogluke** [comment]
Really? I'll try again without @mittovipi's changes and see if I get as far as I did *with* his edits.

**Comment by mittovipi** [comment]
@MatthewPierson  I do not know. but it actually works on High Sierra
https://youtu.be/YH0actPDdiY

**Comment by consolelogluke** [comment]
Yeah, it got way further when using @mittovipi's version than when using the base version.

**Comment by consolelogluke** [comment]
Yeah, it got way further when using @mittovipi's version than when using the base version.

**Comment by consolelogluke** [comment]
Yeah, it got way further when using @mittovipi's version than when using the base version.

**Comment by MatthewPierson** [comment]
My stuff may work on high Sierra I just don’t support it as I cannot test it. As I’ve said twice already, he has not made any functional changes to the script. When you say it got way further what do you specifically mean? If you have changes that add proper support for High Sierra please submit a pull request and I will review the changes. But unless you do that don’t link out to edited copies with no functional changes.

**Comment by consolelogluke** [comment]
He must have changed something because before, futurerestore wouldn't even start but with his changes, the custom iBEC is injected and I get as far as the screen turning green for a second or so.

**Comment by MatthewPierson** [comment]
How many times do I need to say it? Open the scripts and compare them! The file names are different, the language in the logs are different and that is it. If I have missed something during my review of the files then please inform me on what that is and I will apologize and take everything I said back.

**Comment by consolelogluke** [comment]
I no longer have the modified version and it can’t be downloaded anymore but when I had it I noticed some changes in other files, not the scripts.

**Comment by MatthewPierson** [comment]
Closing as nothing is happening here anymore and it got very off topic
