### ISSUE TITLE
Script doesn't stop on errors

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [MatthewPierson/1033-OTA-Downgrader#14]
The script doesn't stop on errors like "file not found" and problems with the dependencies (brew link did not work for wget bc of permission problems). 
Had also some problems extracting from my ipsw as my system language was set to Russian and the Terminal did not recognize some Folders because of the cyrillic chracters.

The script just continued as if everything worked.
After I found all errors manually and fixed them everything went fine

![Bildschirmfoto 2019-10-13 um 02 33 10](https://user-images.githubusercontent.com/20713070/66709332-e7518200-ed61-11e9-9227-3e30d2ab4c0b.png)
![Bildschirmfoto 2019-10-13 um 02 33 24](https://user-images.githubusercontent.com/20713070/66709333-e7518200-ed61-11e9-8f8d-fe904e573582.png)

**Comment by consolelogluke** [comment]
Stopping the script when there’s an error isn’t particularly ideal when using shell scripts from my understanding. You would need to check after every single command what the status of that command was which can get very tedious.

**Comment by MatthewPierson** [comment]
I might add a few more checks for specific errors but to add checks for everything is just not worth my time to be honest, when it already outputs when something didn't work (for the most part). As for the issues with cyrillic chracters and some folders, I have no idea how I would address that as I have no experience at all with cyrillic chracters and scripts. If you want to submit a pull request with any changes that you made for cyrillic chracters then feel free!

**Comment by 13XxM1CHA3lxX37** [comment]
I see your point the output should be enough with some general knowledge. Maybe the issue helps others discover that they need to check the log.
 The cyrillic characters are a very specific issue, fixed it by changing system language.

**Comment by jeffreyvdhondel** [comment]
Maybe you could set the LC_CTYPE/LC_ALL to prevent this issue with the cyrillic characters :)
