### ISSUE TITLE
rmsigchks.py error

### ISSUE THREAD

**Issue by mgfjxxiexiaolong** [MatthewPierson/1033-OTA-Downgrader#18]
![image](https://user-images.githubusercontent.com/13596540/66717067-8d0afc80-ee07-11e9-9114-643aebddb33c.png)

**Comment by MatthewPierson** [comment]
Try reentering DFU mode and trying pwn.sh again. That is an error that sometimes happens with rmsigchks.py and is usually fixed with a new attempt

**Comment by 13XxM1CHA3lxX37** [comment]
I get this error everytime I run the rmsignchecks script but it works nevertheless. Just ignore it and continue

**Comment by mgfjxxiexiaolong** [comment]
`image not found` when execute './restore.sh'
![image](https://user-images.githubusercontent.com/13596540/66880037-95c02600-eff3-11e9-9f81-d6c0d718ae6c.png)

**Comment by mgfjxxiexiaolong** [comment]
> `image not found` when execute './restore.sh'
> ![image](https://user-images.githubusercontent.com/13596540/66880037-95c02600-eff3-11e9-9f81-d6c0d718ae6c.png)

Fucking successful ! Thanks @MatthewPierson .
