### ISSUE TITLE
prep.sh fails to download files

### ISSUE THREAD

**Issue by gbdhhx** [MatthewPierson/1033-OTA-Downgrader#20]
On a fresh install of Mojave I cannot get prep.sh to install futurerestore, igetnonce, and tsschecker. Brew and git are installed though, install.sh ran fine without errors.
![Screen Shot 2019-10-13 at 11 04 54 PM](https://user-images.githubusercontent.com/25283888/66727533-e24a0c80-ee0d-11e9-90f4-ee86a6332d6d.png)

**Comment by MatthewPierson** [comment]
This looks like an error on your end. wget works fine for fetching those files for me, maybe something in your firewall or network settings is blocking it?
