### ISSUE TITLE
restore.sh FUTURESTORE FAILED

### ISSUE THREAD

**Issue by MGSDS** [MatthewPierson/1033-OTA-Downgrader#26]
I had no errors on previous stages, but during recovery i got an error:"FUTURERESTORE FAILED".iPhone6,2 and Mac OS Catalina. 
P.S. Sorry for my bad English.
<img width="1440" alt="Screenshot 2019-10-16 at 16 25 54" src="https://user-images.githubusercontent.com/40380619/66924122-b9ef2780-f032-11e9-9d2c-d363d63989ad.png">

**Comment by gb160** [comment]
looks like an error with openssl.
Try:
`brew reinstall openssl`
...and see if any errors are reported, then try again.
Catalina is a bit of a headache currently, if you still have no luck then try on Mojave.
