### ISSUE TITLE
futurerestore looks for /rsu instead of /usr 

### ISSUE THREAD

**Issue by ethereus** [MatthewPierson/1033-OTA-Downgrader#27]
Library not loaded: /rsu/local/opt/openssl/lib/libssl.1.0.0.dylib

should be /usr/local/opt/openssl/lib/libssl.1.0.0.dylib

**Comment by MatthewPierson** [comment]
It looks there on purpose. Install.sh creates that folder and sub folders to install Dylibs to. Replacing the ones in /usr can cause bootloops on some machines.

**Comment by ethereus** [comment]
For real ? 

I'm glad I didn't go ahead and add to /usr then.. 
And thanks for the reply.
