### ISSUE TITLE
High Sierra supported or not anybody tested?

### ISSUE THREAD

**Issue by omeryarar** [MatthewPierson/1033-OTA-Downgrader#28]
let me know plz if hs is supported

**Comment by MatthewPierson** [comment]
As the readme states only Mojave is fully supported. Catalina has partial support, with a workaround but no other os.

**Comment by consolelogluke** [comment]
High Sierra fails at the last stage (install.sh). Some guy got it working in #10 but @MatthewPierson removed the download because he didn't think it fixed anything

**Comment by MatthewPierson** [comment]
I removed it because it had no actual changes. He never replied with what he "changed" to make it work so as far as I'm concerned there was never HS support.

**Comment by Lengran1992** [comment]
Same issue on High Sierra

**Comment by consolelogluke** [comment]
@MatthewPierson I’m not going to start arguing about it but I do want to mention that it *did* work though

**Comment by MatthewPierson** [comment]
Then as I said before, show me what was changed. I'm fine with admitting I was wrong and apologizing if I'm shown what the changes were that fixed it on HS.

**Comment by consolelogluke** [comment]
Do you have the modified version? I deleted it after using it.

**Comment by Lengran1992** [comment]
Solved!
No modified version,just replace with old version futurestore.
