### ISSUE TITLE
got a problem when execute "./prep.sh"

### ISSUE THREAD

**Issue by mgfjxxiexiaolong** [MatthewPierson/1033-OTA-Downgrader#3]
![image](https://user-images.githubusercontent.com/13596540/66694972-1bd72680-eced-11e9-80ac-c69a702a6abe.png)

**Comment by MatthewPierson** [comment]
Has already been fixed in latest version. Please update and try again!

**Comment by mgfjxxiexiaolong** [comment]
got a problem when execute "./pwn.sh"
![image](https://user-images.githubusercontent.com/13596540/66696149-01f11000-ecfc-11e9-8c5d-75d12be07a79.png)

**Comment by gb160** [comment]
> got a problem when execute "./pwn.sh"
> ![image](https://user-images.githubusercontent.com/13596540/66696149-01f11000-ecfc-11e9-8c5d-75d12be07a79.png)
> ![image](https://user-images.githubusercontent.com/13596540/66696334-bfc8ce00-ecfd-11e9-8854-4fe5af19bab0.png)

Looks like your phone isn't in DFU mode.

**Comment by MatthewPierson** [comment]
Just keep trying. Success rate is low as noted in the script

**Comment by mgfjxxiexiaolong** [comment]
I got this right now. It seems failed. I still on ios12.
![image](https://user-images.githubusercontent.com/13596540/66697673-7337bf80-ed0a-11e9-90d5-fa3a85dff572.png)

**Comment by delterous** [comment]
Im trying to use it on an iPad mini 2 and still failing at pwn.sh

success rate must be really bad

**Comment by mgfjxxiexiaolong** [comment]
> Im trying to use it on an iPad mini 2 and still failing at pwn.sh
> 
> success rate must be really bad

I failed in this step because of entering wrong mode, the phone is black on screen in DFU mode, make sure that.

**Comment by gb160** [comment]
> I got this right now. It seems failed. I still on ios12.
> ![image](https://user-images.githubusercontent.com/13596540/66697673-7337bf80-ed0a-11e9-90d5-fa3a85dff572.png)

Catalina right?
That looks like something’s gone wrong in the install.sh.

**Comment by Starbix** [comment]
@mgfjxxiexiaolong Like @gb160 said that's because of an error in `install.sh`. `install.sh` tries to create a folder `/rsu` which fails in Catalina because it now uses a read-only system volume.
You need to disable SIP and then remount the system volume with read/write like this: `sudo mount -uw /`

**Comment by stratm0r** [comment]
Will it work with OS X Mavericks?

**Comment by mgfjxxiexiaolong** [comment]
> @mgfjxxiexiaolong Like @gb160 said that's because of an error in `install.sh`. `install.sh` tries to create a folder `/rsu` which fails in Catalina because it now uses a read-only system volume.
> You need to disable SIP and then remount the system volume with read/write like this: `sudo mount -uw /`

Im on Mojave....
![image](https://user-images.githubusercontent.com/13596540/66698966-5a80d700-ed15-11e9-8386-d4db4aed8fce.png)

**Comment by Starbix** [comment]
> Im on Mojave....
> ![image](https://user-images.githubusercontent.com/13596540/66698966-5a80d700-ed15-11e9-8386-d4db4aed8fce.png)

Is the /rsu directory present?

**Comment by MatthewPierson** [comment]
@mgfjxxiexiaolong I would create a 35GB ish partition and install macos Mojave to it. Then run all the scripts there

**Comment by mgfjxxiexiaolong** [comment]
> > Im on Mojave....
> > ![image](https://user-images.githubusercontent.com/13596540/66698966-5a80d700-ed15-11e9-8386-d4db4aed8fce.png)
> 
> Is the /rsu directory present?

Of course.
![image](https://user-images.githubusercontent.com/13596540/66699099-68832780-ed16-11e9-9a34-628053779b73.png)

**Comment by mgfjxxiexiaolong** [comment]
> @mgfjxxiexiaolong I would create a 35GB ish partition and install macos Mojave to it. Then run all the scripts there

OK, Wait for goods news.

**Comment by liuhouer** [comment]
![image](https://user-images.githubusercontent.com/2586497/66709479-eafffb80-ed97-11e9-8ccd-26e89e66ac02.png)

mojave 10.14.6

**Comment by cuiyihaohao** [comment]
> ![image](https://user-images.githubusercontent.com/2586497/66709479-eafffb80-ed97-11e9-8ccd-26e89e66ac02.png)
> 
> mojave 10.14.6 with ipad mini2 DFU mode connect my mac

在这里键入ipad或者iPhone，他问你是ipad或者是iPhone而不是问你是否降级。

**Comment by MatthewPierson** [comment]
That error is fixed a few commits ago. Please open new issues instead of adding to old ones @liuhouer

**Comment by liuhouer** [comment]
> > ![image](https://user-images.githubusercontent.com/2586497/66709479-eafffb80-ed97-11e9-8ccd-26e89e66ac02.png)
> > mojave 10.14.6 with ipad mini2 DFU mode connect my mac
> 
> 在这里键入ipad或者iPhone，他问你是ipad或者是iPhone而不是问你是否降级。

Thanks bro... I try again

**Comment by mgfjxxiexiaolong** [comment]
[https://github.com/MatthewPierson/1033-OTA-Downgrader/issues/18](url)
