### ISSUE TITLE
request for iphone se support

### ISSUE THREAD

**Issue by xdumengyu** [MatthewPierson/1033-OTA-Downgrader#40]
This is so great to be able to downgrade, I'm a developer, recently I upgraded my iphone se to ios13 and found I can't capture gpu frame from Xcode, when I use iphone se 11 from my colleage, the problem has gone,  it would be great if you provide support for iphone se, thanks in advance

**Comment by consolelogluke** [comment]
iPhone SE doesn’t have A7 processor so it won’t work
