### ISSUE TITLE
restore does not match APTicket

### ISSUE THREAD

**Issue by narsolo** [MatthewPierson/1033-OTA-Downgrader#55]
WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1
Found device in Recovery mode
Device already in Recovery mode
Found device in Recovery mode
Identified device as j85ap, iPad4,4
Extracting BuildManifest from IPSW
Product Version: 10.3.3
Product Build: 14G60 Major: 14
Device supports Image4: true
Got APNonce from device: b8 03 b8 b5 bb b7 27 eb cd 70 f7 05 f1 f0 3e b4 5c ee ca 08
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
[Error] im4m_buildidentity_check_cb: can't find any identity which matches all hashes inside IM4M
[Error] getBuildIdentityForIM4M: found buildidentiy, but can't read information
[Error] BuildIdentity selected for restore does not match APTicket

BuildIdentity selected for restore:
BuildNumber : 14G60
BuildTrain : Greensburg
DeviceClass : j85ap
FDRSupport : NO
RestoreBehavior : Erase
Variant : Customer Erase Install (IPSW)

**Comment by MatthewPierson** [comment]
That is not an issue, it is meant to say that. Just let the restore continue
