### ISSUE TITLE
No matching processes...

### ISSUE THREAD

**Issue by cryptlord4** [MatthewPierson/1033-OTA-Downgrader#64]
<img width="556" alt="스크린샷 2019-11-10 오후 6 34 46" src="https://user-images.githubusercontent.com/57585849/68541913-d0e22900-03e8-11ea-8532-b615f698bf09.png">
<img width="565" alt="스크린샷 2019-11-10 오후 6 32 48" src="https://user-images.githubusercontent.com/57585849/68541912-d0e22900-03e8-11ea-8970-d905b919a05a.png">

Mac OS : catalina 10.15
iPhone 6.2, global

How can I resolve this error?

**Comment by DEV1L666** [comment]
Did you manage to downgrade it? Because there are files missing and mine doesn't go any further than [Error] Fail code=-3
