### ISSUE TITLE
Failed with errorcode=-44

### ISSUE THREAD

**Issue by px123zx** [MatthewPierson/1033-OTA-Downgrader#69]
The last step

BuildIdentiy valid for the APTicket:
IM4M is not valid for any restore within the Buildmanifest
This APTicket can't be used for restoring this firmware
[Error] APTicket can't be used for this restore
Done: restoring failed.
Failed with errorcode=-44
Cleaning up :D

Is the shsh2 not right ？ Or some else problem ？
How to deal whit it?
Thank you for you if you can help me

**Comment by Merculous** [comment]
Please send your log. There's is no obvious issue to confront.
