### ISSUE TITLE
recovery mode

### ISSUE THREAD

**Issue by GhostHalston** [MatthewPierson/1033-OTA-Downgrader#7]
can he works in recovery mode?
My bouton home doesn't work.

**Comment by mgfjxxiexiaolong** [comment]
大佬 button 写错了。。。。

**Comment by onny** [comment]
> can he works in recovery mode?
> My bouton home doesn't work.

I don't think so, you'll need the home button

**Comment by consolelogluke** [comment]
It needs to be DFU mode. Also in the future don't create issues for questions.
