### ISSUE TITLE
Either unsupported device or no device found

### ISSUE THREAD

**Issue by nettoarnaldo** [MatthewPierson/1033-OTA-Downgrader#70]
I am getting an error message when trying to downgrade my iPhone 5S (iPhone6,2).

The process is terminated shortly after the message:

Either unsupported device or no device found. \
Exiting .. \

How can I fix this?

NOTE: I am using the files from your last update

[log.zip](https://github.com/MatthewPierson/1033-OTA-Downgrader/files/3840838/log.zip)
.

**Comment by Merculous** [comment]
Thanks for the submission. I'll look into this as it seems like many are having issues with igetnonce.

**Comment by Leadereric** [comment]
when start anything, don't forget input cd 1033-OTA-........, because the igetnonce is in this folder........already tested.....
