### ISSUE TITLE
IOCreatePlugInterfaceforService failed

### ISSUE THREAD

**Issue by q1f3** [MatthewPierson/1033-OTA-Downgrader#71]
IOCreatePlugInInterfaceForService failed 0xe00002be
mac ver MacOS Mojave 10.14.5

**Comment by Merculous** [comment]
This is normal. For some reason, starting from MacOS Mojave, lsusb prints this every time. There is no reasonable nor obvious impact. I will be closing this issue as this does not impact the scripts performance.
