### ISSUE TITLE
macOS Catalina 10.15.1

### ISSUE THREAD

**Issue by KillaRhymes** [MatthewPierson/1033-OTA-Downgrader#81]
Did somebody try this on a macOS Catalina, version 10.15.1? And did succeed?
I tried it at least 20 times and it didn't work. 
At the end, it says 

[Error] Fail code=-15
Failed with errorcode=-15
Cleaning up :D
dummy_file
ipsw
If you see this, we're done! Shoutout to the devs and Matty for making this possible! - Merculous
P.S. You know, this could look even better and be even easier if we port it to Python :D

but nothing happens on my phone.

**Comment by MatthewPierson** [comment]
I need the full log to be able to help you
