### ISSUE TITLE
I'm not very sure if this is the error that is supposed to happen up to 40 times

### ISSUE THREAD

**Issue by ilegitimado** [MatthewPierson/1033-OTA-Downgrader#9]
![Captura de pantalla (10)](https://user-images.githubusercontent.com/50776178/66703830-fced8a00-ed16-11e9-98bc-4d0369b9a745.png)

**Comment by consolelogluke** [comment]
Doesn't work in a virtual machine. If you don't have a Mac you could use Hackintosh.

**Comment by 0x0luke** [comment]
If you fully pass the USB controller into a VM, it *SHOULD* work, but I have no idea how that's done in VMware.

**Comment by consolelogluke** [comment]
People have tried before with no success

**Comment by 0x0luke** [comment]
Qwerty got this working with his hackintosh - https://twitter.com/qwertyoruiopz/status/1181875003811418112

**Comment by consolelogluke** [comment]
Ooh I interpreted your reply as USB pass through.

**Comment by ilegitimado** [comment]
I can connect the iPhone to my Windows or to my VM. I will try to install hackintosh on a spare hard drive I have just for this. Thank you.
