### ISSUE TITLE
[Error] [TSSR] Error:

### ISSUE THREAD

**Issue by gblgbl1234** [MatthewPierson/1033-OTA-Downgrader#99]
[TSSC] manually specified ECID to use, parsed "5557828602064" to dec:5557828602064 hex:50e086648d0
[TSSC] opening manifests/BuildManifest_iPhone6,2_1033_OTA.plist
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[Error] [TSSR] Error: could not get id0 for installType=Update
[WARNING] [TSSR] failed to build tssrequest for alternative installType
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)
Saved shsh blobs!

iOS 10.3.3 for device iPhone6,2 IS being signed!
shsh/5557828602064_iPhone6,2_10.3.3-14G60_7088be01bbddfd63eb7590dba8bec8c5edc4543a.shsh2 -> shsh/stitch.shsh2
img4tool version: 0.180-562d979a6a3b7d0600b0c1ad8ac1731502f39827
Compiled with plist: YES
Created IMG4 file at iBSS.img4
img4tool version: 0.180-562d979a6a3b7d0600b0c1ad8ac1731502f39827
Compiled with plist: YES
Created IMG4 file at iBEC.img4
iBSS.img4 -> ipsw/Firmware/dfu/iBSS.iphone6.RELEASE.im4p
iBEC.img4 -> ipsw/Firmware/dfu/iBEC.iphone6.RELEASE.im4p
  adding: 058-74917-062.dmg (deflated 1%)
  adding: 058-74940-063.dmg (deflated 17%)
  adding: 058-75381-062.dmg (deflated 17%)
  adding: BuildManifest.plist (deflated 95%)
  adding: Firmware/ (stored 0%)
  adding: Firmware/aopfw.im4p (deflated 45%)
  adding: Firmware/usr/ (stored 0%)
  adding: Firmware/usr/local/ (stored 0%)
  adding: Firmware/usr/local/standalone/ (stored 0%)
  adding: Firmware/dfu/ (stored 0%)
  adding: Firmware/dfu/iBEC.n69.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/dfu/iBSS.n69u.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/dfu/iBSS.iphone6.RELEASE.im4p (deflated 51%)
  adding: Firmware/dfu/iBEC.n69.RELEASE.im4p (deflated 0%)
  adding: Firmware/dfu/iBEC.n69u.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/dfu/iBEC.n69u.RELEASE.im4p (deflated 0%)
  adding: Firmware/dfu/iBSS.iphone6.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/dfu/iBEC.iphone6.RELEASE.im4p (deflated 49%)
  adding: Firmware/dfu/iBSS.n69.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/dfu/iBEC.iphone6.RELEASE.im4p.plist (deflated 28%)
  adding: Firmware/dfu/iBSS.n69u.RELEASE.im4p (deflated 0%)
  adding: Firmware/dfu/iBSS.n69.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/ (stored 0%)
  adding: Firmware/all_flash/DeviceTree.n51ap.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/sep-firmware.n51.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/iBoot.n69u.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/sep-firmware.n51.RELEASE.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/LLB.n69.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s5l8960x.im4p (deflated 69%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s8000.im4p.plist (deflated 38%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s8003.im4p (deflated 77%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8000.im4p (deflated 13%)
  adding: Firmware/all_flash/sep-firmware.n69u.RELEASE.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s8003.im4p (deflated 20%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s5l8960x.im4p (deflated 77%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s5l8960x.im4p (deflated 9%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s8000.im4p (deflated 69%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s8000.im4p (deflated 9%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8000.im4p (deflated 72%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s5l8960x.im4p.plist (deflated 38%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8960x.im4p (deflated 13%)
  adding: Firmware/all_flash/sep-firmware.n69.RELEASE.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/DeviceTree.n69uap.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/LLB.iphone6.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/DeviceTree.n69uap.im4p (deflated 82%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s8000.im4p (deflated 12%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8960x.im4p (deflated 72%)
  adding: Firmware/all_flash/LLB.n69u.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/LLB.n69.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/LLB.iphone6.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s5l8960x.im4p (deflated 12%)
  adding: Firmware/all_flash/iBoot.n69u.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s8003.im4p (deflated 12%)
  adding: Firmware/all_flash/iBoot.iphone6.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s8000.im4p (deflated 12%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s8003.im4p (deflated 12%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/sep-firmware.n69.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s5l8960x.im4p (deflated 12%)
  adding: Firmware/all_flash/DeviceTree.n69ap.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/iBoot.n69.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/sep-firmware.n53.RELEASE.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s8003.im4p (deflated 69%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s8003.im4p (deflated 9%)
  adding: Firmware/all_flash/DeviceTree.n69ap.im4p (deflated 82%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s5l8960x.im4p (deflated 20%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8003.im4p (deflated 72%)
  adding: Firmware/all_flash/iBoot.n69.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/sep-firmware.n69u.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/DeviceTree.n53ap.im4p (deflated 83%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8003.im4p (deflated 13%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s8000.im4p (deflated 20%)
  adding: Firmware/all_flash/DeviceTree.n53ap.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s8000.im4p (deflated 77%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/iBoot.iphone6.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/sep-firmware.n53.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/DeviceTree.n51ap.im4p (deflated 83%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s8003.im4p.plist (deflated 38%)
  adding: Firmware/all_flash/LLB.n69u.RELEASE.im4p (deflated 0%)
  adding: Firmware/Mav10-5.62.00.Release.plist (deflated 23%)
  adding: Firmware/Mav7Mav8-7.60.00.Release.plist (deflated 29%)
  adding: Firmware/Mav10-5.62.00.Release.bbfw (deflated 0%)
  adding: Firmware/Mav7Mav8-7.60.00.Release.bbfw (deflated 0%)
  adding: Restore.plist (deflated 84%)
  adding: kernelcache.release.iphone6 (deflated 6%)
  adding: kernelcache.release.iphone8b (deflated 6%)
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
Version: b9d193aa6e6d24421094873c830692d02d8b32f5 - 304
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified ECID to use, parsed "5557828602064" to dec:5557828602064 hex:50e086648d0
[TSSC] manually specified apnonce to use, parsed "7ce1657233867e988e1b48988ef98fc28ddf20f5" to hex:7ce1657233867e988e1b48988ef98fc28ddf20f5
[TSSC] opening manifests/BuildManifest_iPhone6,2_1033_OTA.plist
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[Error] [TSSR] Error: could not get id0 for installType=Update
[WARNING] [TSSR] failed to build tssrequest for alternative installType
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)
Saved shsh blobs!

iOS 10.3.3 for device iPhone6,2 IS being signed!
5557828602064_iPhone6,2_10.3.3-14G60_7ce1657233867e988e1b48988ef98fc28ddf20f5.shsh -> shsh/apnonce.shsh2
Done prepping files! Time to downgrade!!!
****RESTORING!****
Waiting for device to reconnect...
./restore.sh: line 292: futurerestore: command not found
Cleaning up :D
dummy_file
iBSS.im4p
iBSS.img4
iBSS.iphone6.RELEASE.im4p
iBSS.prepatched
iBSS.raw
iBEC.im4p
iBEC.img4
iBEC.iphone6.RELEASE.im4p
iBEC.prepatched
iBEC.raw
Mav7Mav8-7.60.00.Release.bbfw
sep-firmware.n53.RELEASE.im4p
ipsw/Firmware/aopfw.im4p
ipsw/Firmware/usr/local/standalone
ipsw/Firmware/usr/local
ipsw/Firmware/usr
ipsw/Firmware/dfu/iBEC.n69.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBSS.n69u.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBSS.iphone6.RELEASE.im4p
ipsw/Firmware/dfu/iBEC.n69.RELEASE.im4p
ipsw/Firmware/dfu/iBEC.n69u.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBEC.n69u.RELEASE.im4p
ipsw/Firmware/dfu/iBSS.iphone6.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBEC.iphone6.RELEASE.im4p
ipsw/Firmware/dfu/iBSS.n69.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBEC.iphone6.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBSS.n69u.RELEASE.im4p
ipsw/Firmware/dfu/iBSS.n69.RELEASE.im4p
ipsw/Firmware/dfu
ipsw/Firmware/all_flash/DeviceTree.n51ap.im4p.plist
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8000.im4p.plist
ipsw/Firmware/all_flash/sep-firmware.n51.RELEASE.im4p
ipsw/Firmware/all_flash/iBoot.n69u.RELEASE.im4p
ipsw/Firmware/all_flash/sep-firmware.n51.RELEASE.im4p.plist
ipsw/Firmware/all_flash/LLB.n69.RELEASE.im4p
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/applelogo@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8000.im4p
ipsw/Firmware/all_flash/sep-firmware.n69u.RELEASE.im4p.plist
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/applelogo@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/applelogo@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s8000.im4p
ipsw/Firmware/all_flash/applelogo@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8960x.im4p
ipsw/Firmware/all_flash/sep-firmware.n69.RELEASE.im4p.plist
ipsw/Firmware/all_flash/DeviceTree.n69uap.im4p.plist
ipsw/Firmware/all_flash/LLB.iphone6.RELEASE.im4p.plist
ipsw/Firmware/all_flash/DeviceTree.n69uap.im4p
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s8000.im4p.plist
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8960x.im4p
ipsw/Firmware/all_flash/LLB.n69u.RELEASE.im4p.plist
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/LLB.n69.RELEASE.im4p.plist
ipsw/Firmware/all_flash/LLB.iphone6.RELEASE.im4p
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/iBoot.n69u.RELEASE.im4p.plist
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/iBoot.iphone6.RELEASE.im4p.plist
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/sep-firmware.n69.RELEASE.im4p
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/DeviceTree.n69ap.im4p.plist
ipsw/Firmware/all_flash/iBoot.n69.RELEASE.im4p
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s8003.im4p.plist
ipsw/Firmware/all_flash/sep-firmware.n53.RELEASE.im4p.plist
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/applelogo@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/DeviceTree.n69ap.im4p
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s8003.im4p
ipsw/Firmware/all_flash/iBoot.n69.RELEASE.im4p.plist
ipsw/Firmware/all_flash/sep-firmware.n69u.RELEASE.im4p
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/DeviceTree.n53ap.im4p
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8003.im4p
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/DeviceTree.n53ap.im4p.plist
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/iBoot.iphone6.RELEASE.im4p
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8003.im4p.plist
ipsw/Firmware/all_flash/sep-firmware.n53.RELEASE.im4p
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/DeviceTree.n51ap.im4p
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/applelogo@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/LLB.n69u.RELEASE.im4p
ipsw/Firmware/all_flash
ipsw/Firmware/Mav10-5.62.00.Release.plist
ipsw/Firmware/Mav7Mav8-7.60.00.Release.plist
ipsw/Firmware/Mav10-5.62.00.Release.bbfw
ipsw/Firmware/Mav7Mav8-7.60.00.Release.bbfw
ipsw/Firmware
ipsw/058-75381-062.dmg
ipsw/kernelcache.release.iphone8b
ipsw/058-74940-063.dmg
ipsw/Restore.plist
ipsw/kernelcache.release.iphone6
ipsw/BuildManifest.plist
ipsw/058-74917-062.dmg
ipsw/._058-74917-062.dmg
ipsw
downgrade.ipsw
iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw
If you see this, we're done! Shoutout to the devs and Matty for making this possible! - Merculous
P.S. You know, this could look even better and be even easier if we port it to Python :D

**Comment by MatthewPierson** [comment]
Don't use this script anymore, use [Viuex](https://github.com/MatthewPierson/Vieux) instead as it is much more up to date/works much better.
